### ISSUE TITLE
[BUG] Unable to create event rule - error in /api/v2.0/event/<signature>/new_related_events

### ISSUE THREAD

**Issue by jtavan** [reflexsoar/reflex-api#162]
**Describe the bug**
Clicking the blue "Create Event Rule" button in the Event Queue list results in a 500 error returning from /api/v2.0/event/<signature>/new_related_events and no create event rule dialog box opens.

**To Reproduce**
1. Go to Events -> Queue
2. Click on a blue 'Create Event Rule' button
3. See error in console log

**Expected behavior**
A new Event Rule dialog box opens.

**Screenshots**
Reflex API logs the following trace:

> 2022-05-12 14:59:37,031 - app - ERROR - Exception on /api/v2.0/event/1de521dbef3030460daea14fc5c29ebb/new_related_events [GET]
> Traceback (most recent call last):
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
>     resp = resource(*args, **kwargs)
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
>     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/marshalling.py", line 248, in wrapper
>     resp = f(*args, **kwargs)
>   File "/app/api_v2/utils.py", line 204, in wrapper
>     return f(*args, **kwargs, current_user=current_user)
>   File "/app/api_v2/utils.py", line 250, in wrapper
>     return f(*args, **kwargs)
>   File "/app/api_v2/resource/event.py", line 1781, in get
>     events = Event.get_by_signature_and_status(signature=signature, status='New', all_events=True)
>   File "/app/api_v2/model/event.py", line 311, in get_by_signature_and_status
>     response = list(response.scan())
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/elasticsearch_dsl/search.py", line 731, in scan
>     for hit in scan(es, query=self.to_dict(), index=self._index, **self._params):
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 576, in scan
>     resp = client.search(**search_kwargs)
>   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
>     return func(*args, params=params, headers=headers, **kwargs)
> TypeError: search() got an unexpected keyword argument 'from'
> 

**Additional context**
I have installed ReflexSOAR in a docker-compose similar to the Quick Start procedure, but with our existing Elasticsearch 7.17 cluster as a storage back end.

**Comment by SMAPPER** [comment]
Out of curiosity, can you try flipping your input distro from elasticsearch to opensearch and save it. Then see if this error persists. The opensearch distro controls how Python connects to OpenSearch or Elasticsearch and is compatible with Elasticsearch version 7.17. We've recently seen some odd issues with the Elasticsearch python code and I want to rule it out.

**Comment by SMAPPER** [comment]
Also, the main setting to try is changing your environmental variable in the docker-compose for reflex-api to have this:

- REFLEX_ES_DISTRO=opensearch

Again, this will work with your Elasticsearch 7.17.0 cluster and will rule out a python library issue with Elasticsearch. If you could make this change and restart reflex-api and let us know, I'd appreciate it.

**Comment by SMAPPER** [comment]
FYI - We just confirmed this bug in our lab. This is the issue. We are implementing a patch but for right now the workaround is to set the environmental variable of:

REFLEX_ES_DISTRO=opensearch

**Comment by jtavan** [comment]
Confirmed - with REFLEX_ES_DISTRO set to opensearch the error does not occur. Thanks!
